services:
  frontend:
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  # Ensure node_modules are stored inside the container
    environment:
      NODE_ENV: development